-- DMS user keybind overrides (edit via Control Center or dms; do not remove this header)

hl.unbind("Print")
hl.bind("Print", hl.dsp.exec_cmd("dms screenshot -d /tmp"), { description = "dms screenshot" })
hl.unbind("SUPER + R")
hl.bind("SUPER + R", hl.dsp.exec_cmd("dms ipc call spotlight toggle"), { description = "Spotlight" })
hl.unbind("SUPER + T")
hl.bind("SUPER + T", hl.dsp.exec_cmd("ghostty"), { description = "Terminal (ghostty)" })
hl.unbind("ALT + SHIFT + TAB")
hl.bind("ALT + SHIFT + TAB", hl.dsp.window.cycle_next({ next = false }), { description = "Switch to previous window" })
hl.unbind("ALT + TAB")
hl.bind("ALT + TAB", hl.dsp.window.cycle_next(), { description = "Switch to next window" })
hl.unbind("SUPER + F")
hl.bind("SUPER + F", hl.dsp.window.float({ action = "toggle" }), { description = "Toggle floating" })
hl.unbind("SUPER + space")
hl.bind("SUPER + space", hl.dsp.exec_raw("hyprctl switchxkblayout all next"), { description = "Switch keyboard layout" })
hl.bind("F23", hl.dsp.send_shortcut({ mods = "CTRL + SHIFT", key = "D", window = "class:^(vesktop)$" }), { description = "Vesktop toggle deafen" })
hl.bind("F24", hl.dsp.send_shortcut({ mods = "CTRL + SHIFT", key = "M", window = "class:^(vesktop)$" }), { description = "Vesktop toggle mute" })
hl.unbind("SUPER + L")
hl.bind("SUPER + L", hl.dsp.exec_cmd("dms ipc call lock lock"), { description = "Lock screen" })
hl.unbind("SUPER + ALT + L")
hl.unbind("SUPER + SHIFT + L")
hl.unbind("SUPER + CTRL + L")
hl.unbind("SUPER + SHIFT + CTRL + L")

hl.bind("SUPER + SUPER_L", hl.dsp.exec_cmd("/home/soulis/.local/bin/dms-game-overlay"), { release = true, description = "Toggle Game Control Center" })
