-- DMS user keybind overrides (edit via Control Center or dms; do not remove this header)

hl.unbind("SUPER + L")
hl.bind("SUPER + L", hl.dsp.exec_cmd("dms ipc call lock lock"), { description = "dms ipc call lock lock" })
hl.unbind("SUPER + R")
hl.bind("SUPER + R", hl.dsp.exec_cmd("dms ipc call spotlight-bar toggle"), { description = "dms ipc call spotlight-bar toggle" })
hl.unbind("ALT + Tab")
hl.bind("ALT + Tab", hl.dsp.window.cycle_next({ next = false }), { description = "Cycle Previous Window" })
hl.unbind("ALT + space")
hl.unbind("SUPER + ALT + L")
hl.unbind("SUPER + CTRL + F")
hl.unbind("SUPER + F")
hl.bind("SUPER + F", hl.dsp.window.float({ action = "toggle" }), { description = "Toggle Floating" })
hl.unbind("SUPER + H")
hl.unbind("SUPER + J")
hl.unbind("SUPER + K")
hl.unbind("SUPER + P")
hl.unbind("SUPER + down")
hl.unbind("SUPER + left")
hl.unbind("SUPER + right")
hl.unbind("SUPER + space")
hl.unbind("SUPER + up")
hl.bind("SUPER + ALT + 2", hl.dsp.window.move({ workspace = "2" }), { description = "Move window to workspace 2" })
