-- Auto-generated by DMS Matugen hook — do not edit manually.
-- Remove require("dms.colors") from hyprland.lua to override.

hl.config({
	general = {
		col = {
			active_border = "rgb(b8a8f0)",
			inactive_border = "rgb(c9b8d9)",
		},
	},
	group = {
		col = {
			border_active = "rgb(b8a8f0)",
			border_inactive = "rgb(c9b8d9)",
			border_locked_active = "rgb(f38ba8)",
			border_locked_inactive = "rgb(c9b8d9)",
		},
		groupbar = {
			col = {
				active = "rgb(b8a8f0)",
				inactive = "rgb(c9b8d9)",
				locked_active = "rgb(f38ba8)",
				locked_inactive = "rgb(c9b8d9)",
			},
		},
	},
})
