-- Hyprland configuration (Lua) — https://wiki.hypr.land/Configuring/Start/
-- Laptop Profile (ThinkPad TrackPoint, Lid DPMS blanking, single-screen)

hl.config({ autogenerated = false })

-------------------------------
---- ENVIRONMENT VARIABLES ----
-------------------------------

hl.env("QT_QPA_PLATFORM", "wayland")
hl.env("QT_QPA_PLATFORMTHEME", "gtk3")
hl.env("QT_QPA_PLATFORMTHEME_QT6", "gtk3")
hl.env("ELECTRON_OZONE_PLATFORM_HINT", "auto")
hl.env("TERMINAL", "ghostty")

-------------------
---- AUTOSTART ----
-------------------

-- DMS_STARTUP_BEGIN
hl.on("hyprland.start", function()
	hl.exec_cmd("dbus-update-activation-environment --systemd --all")
	hl.exec_cmd("systemctl --user start hyprland-session.target")
end)
-- DMS_STARTUP_END

-- User autostart
hl.on("hyprland.start", function()
	hl.exec_cmd("wl-paste --watch cliphist store")
	hl.exec_cmd("/usr/lib/mate-polkit/polkit-mate-authentication-agent-1")
end)

-----------------------
---- LOOK AND FEEL ----
-----------------------

hl.config({
	binds = {
		allow_pin_fullscreen = true,
	},
	input = {
		kb_layout = "us,gr",
		kb_options = "grp:win_space_toggle",
		repeat_delay = 300,
		numlock_by_default = true,
		-- Click to activate (Win11). Hovering a float must not yank focus.
		follow_mouse = 2,
		float_switch_override_focus = 0,
		mouse_refocus = false,
		accel_profile = "flat",
		sensitivity = 0.0,
		touchpad = {
			tap_to_click = true,
			natural_scroll = true,
		},
	},
	general = {
		gaps_in = 5,
		gaps_out = 5,
		border_size = 2,
		layout = "dwindle",
	},
	decoration = {
		rounding = 12,
		border_part_of_window = false,
		active_opacity = 1.0,
		inactive_opacity = 1.0,
		shadow = {
			enabled = true,
			range = 30,
			render_power = 5,
			offset = "0 5",
			color = "rgba(00000070)",
		},
	},
	misc = {
		disable_hyprland_logo = true,
		disable_splash_rendering = true,
	},
	dwindle = {
		preserve_split = true,
	},
	master = {
		mfact = 0.5,
	},
})

-- ThinkPad pad can show up as RMI4/I2C or old PS/2. Disable both so a
-- driver flip after reboot cannot turn it back on. TrackPoint stays.
hl.device({
	name = "synaptics-tm2722-001",
	enabled = false,
})
hl.device({
	name = "synps/2-synaptics-touchpad",
	enabled = false,
})

hl.animation({ leaf = "windowsIn", enabled = true, speed = 3, bezier = "default" })
hl.animation({ leaf = "windowsOut", enabled = true, speed = 3, bezier = "default" })
hl.animation({ leaf = "workspaces", enabled = true, speed = 5, bezier = "default" })
hl.animation({ leaf = "windowsMove", enabled = true, speed = 4, bezier = "default" })
hl.animation({ leaf = "fade", enabled = true, speed = 3, bezier = "default" })
hl.animation({ leaf = "border", enabled = true, speed = 3, bezier = "default" })

--------------------------------
---- WINDOWS AND WORKSPACES ----
--------------------------------

hl.window_rule({ match = { class = "^(org\\.wezfurlong\\.wezterm)$" }, tile = true })
hl.window_rule({ match = { class = "^(org\\.gnome\\.)" }, rounding = 12 })
hl.window_rule({ match = { class = "^(gnome-control-center)$" }, tile = true })
hl.window_rule({ match = { class = "^(pavucontrol)$" }, tile = true })
hl.window_rule({ match = { class = "^(nm-connection-editor)$" }, tile = true })
hl.window_rule({ match = { class = "^(org\\.gnome\\.Calculator)$" }, float = true })
hl.window_rule({ match = { class = "^(gnome-calculator)$" }, float = true })
hl.window_rule({ match = { class = "^(galculator)$" }, float = true })
hl.window_rule({ match = { class = "^(blueman-manager)$" }, float = true })
hl.window_rule({ match = { class = "^(org\\.gnome\\.Nautilus)$" }, float = true })
hl.window_rule({ match = { class = "^(xdg-desktop-portal)$" }, float = true })
hl.window_rule({
	match = { class = "^(steam)$", title = "^(notificationtoasts)" },
	no_initial_focus = true,
	pin = true,
})
hl.window_rule({
	match = { title = ".*[Pp]icture[- ][iI]n[- ][pP]icture.*" },
	float = true,
	pin = true,
})
hl.window_rule({ match = { class = "^(zoom)$" }, float = true })
hl.layer_rule({ match = { namespace = "^(quickshell)$" }, no_anim = true })
hl.layer_rule({ match = { namespace = "^dms:.*" }, no_anim = true })

-------------------------
---- DMS FRAGMENTS -----
-------------------------

require("dms.colors")
if not pcall(require, "dms.outputs") then
	hl.monitor({ output = "", mode = "preferred", position = "auto", scale = "auto" })
end
require("dms.layout")
require("dms.cursor")
require("dms.binds")
require("dms.binds-user")
require("dms.windowrules")

-- Inactive color is fully transparent; border is drawn outside the window.
hl.config({
	general = {
		col = {
			inactive_border = "rgba(00000000)",
		},
	},
	decoration = {
		border_part_of_window = false,
	},
	input = {
		follow_mouse = 2,
		float_switch_override_focus = 0,
		mouse_refocus = false,
	},
})

-- Smart borders: disable border when only one tiled window is present
hl.window_rule({
	match = { float = false, workspace = "w[tv1]" },
	border_size = 0,
})
hl.window_rule({
	match = { float = false, workspace = "f[1]" },
	border_size = 0,
})

-- Lid close blanks eDP-1 only. logind must ignore the lid or it still suspends.
hl.bind("switch:on:Lid Switch", function()
	hl.timer(function()
		hl.dispatch(hl.dsp.dpms({ action = "off", monitor = "eDP-1" }))
	end, { timeout = 500, type = "oneshot" })
end, { locked = true, description = "Blank laptop screen on lid close" })

hl.bind("switch:off:Lid Switch", function()
	hl.timer(function()
		hl.dispatch(hl.dsp.dpms({ action = "on", monitor = "eDP-1" }))
	end, { timeout = 500, type = "oneshot" })
end, { locked = true, description = "Wake laptop screen on lid open" })
