-- Hyprland configuration (Lua) — https://wiki.hypr.land/Configuring/Start/
-- Unified base configuration across all machines.
-- DMS-managed fragments live in ~/.config/hypr/dms/ and are required below.

hl.config({ autogenerated = false })

-------------------------------
---- ENVIRONMENT VARIABLES ----
-------------------------------

hl.env("QT_QPA_PLATFORM", "wayland")
hl.env("QT_QPA_PLATFORMTHEME", "gtk3")
hl.env("QT_QPA_PLATFORMTHEME_QT6", "gtk3")
hl.env("ELECTRON_OZONE_PLATFORM_HINT", "auto")
hl.env("TERMINAL", "ghostty")

-------------------
---- AUTOSTART ----
-------------------

-- DMS_STARTUP_BEGIN
hl.on("hyprland.start", function()
	hl.exec_cmd("dbus-update-activation-environment --systemd --all")
	hl.exec_cmd("systemctl --user start hyprland-session.target")
end)
-- DMS_STARTUP_END

-- User autostart
hl.on("hyprland.start", function()
	hl.exec_cmd("wl-paste --watch cliphist store")
end)

-----------------------
---- LOOK AND FEEL ----
-----------------------

hl.config({
	binds = {
		allow_pin_fullscreen = true,
	},
	input = {
		kb_layout = "us,gr",
		kb_options = "",
		repeat_delay = 300,
		numlock_by_default = true,
		-- Click to activate (Win11). Hovering a float must not yank focus.
		follow_mouse = 2,
		float_switch_override_focus = 0,
		mouse_refocus = false,
		accel_profile = "flat",
		sensitivity = 0.0,
		touchpad = {
			tap_to_click = true,
			natural_scroll = true,
		},
	},
	general = {
		allow_tearing = true,
		gaps_in = 5,
		gaps_out = 5,
		border_size = 2,
		layout = "dwindle",
	},
	decoration = {
		rounding = 12,
		border_part_of_window = false,
		active_opacity = 1.0,
		inactive_opacity = 1.0,
		blur = {
			enabled = false,
		},
		shadow = {
			enabled = true,
			range = 30,
			render_power = 5,
			offset = "0 5",
			color = "rgba(00000070)",
		},
	},
	misc = {
		disable_hyprland_logo = true,
		disable_splash_rendering = true,
		vrr = 1,
	},
	cursor = {
		no_hardware_cursors = 0,
		use_cpu_buffer = 0,
		no_warps = true,
	},
	dwindle = {
		preserve_split = true,
	},
	master = {
		mfact = 0.5,
	},
})

-- ThinkPad TrackPoint (disables touchpad to prevent palm jitter; dormant on desktop)
hl.device({
	name = "synaptics-tm2722-001",
	enabled = false,
})
hl.device({
	name = "synps/2-synaptics-touchpad",
	enabled = false,
})

hl.animation({ leaf = "windowsIn", enabled = true, speed = 3, bezier = "default" })
hl.animation({ leaf = "windowsOut", enabled = true, speed = 3, bezier = "default" })
hl.animation({ leaf = "workspaces", enabled = true, speed = 5, bezier = "default" })
hl.animation({ leaf = "windowsMove", enabled = true, speed = 4, bezier = "default" })
hl.animation({ leaf = "fade", enabled = true, speed = 3, bezier = "default" })
hl.animation({ leaf = "border", enabled = true, speed = 3, bezier = "default" })

--------------------------------
---- WINDOWS AND WORKSPACES ----
--------------------------------

-- Stock DMS window / layer rules (user extras live in dms/windowrules.lua)
hl.window_rule({ match = { class = "^(org\\.wezfurlong\\.wezterm)$" }, tile = true })
hl.window_rule({ match = { class = "^(org\\.gnome\\.)" }, rounding = 12 })
hl.window_rule({ match = { class = "^(gnome-control-center)$" }, tile = true })
hl.window_rule({ match = { class = "^(pavucontrol)$" }, tile = true })
hl.window_rule({ match = { class = "^(nm-connection-editor)$" }, tile = true })
hl.window_rule({ match = { class = "^(org\\.gnome\\.Calculator)$" }, float = true })
hl.window_rule({ match = { class = "^(gnome-calculator)$" }, float = true })
hl.window_rule({ match = { class = "^(galculator)$" }, float = true })
hl.window_rule({ match = { class = "^(blueman-manager)$" }, float = true })
hl.window_rule({ match = { class = "^(org\\.gnome\\.Nautilus)$" }, float = true, center = true, size = {1100, 700} })
hl.window_rule({ match = { class = "^(xdg-desktop-portal)$" }, float = true })
hl.window_rule({
	match = { title = ".*[Pp]icture[- ][iI]n[- ][pP]icture.*" },
	float = true,
	pin = true,
})
hl.window_rule({ match = { class = "^(zoom)$" }, float = true })
hl.layer_rule({ match = { namespace = "^(quickshell)$" }, no_anim = true })
hl.layer_rule({ match = { namespace = "^dms:.*" }, no_anim = true })

-------------------------
---- DMS FRAGMENTS -----
-------------------------

require("dms.colors")
if not pcall(require, "dms.outputs") then
	hl.monitor({ output = "", mode = "preferred", position = "auto", scale = "auto" })
end
require("dms.layout")
require("dms.cursor")
require("dms.floating-mode")
require("dms.mosaic")
require("dms.layout-manager")
require("dms.binds")
require("dms.binds-user")
require("dms.windowrules")
require("dms.steam-toasts")

-- Inactive color is fully transparent; border is drawn outside the window.
hl.config({
	general = {
		col = {
			inactive_border = "rgba(00000000)",
		},
	},
	decoration = {
		border_part_of_window = false,
	},
	input = {
		follow_mouse = 2,
		float_switch_override_focus = 0,
		mouse_refocus = false,
	},
})

-- Hyprland's CLayerSurface::onMap() forces pointer focus onto any newly mapped
-- OnDemand/Exclusive layer, even when the cursor is still over the bar. Clicks
-- then go to that layer (or nowhere, if they land in an input-region hole) until
-- the mouse moves. Re-hit-test pointer focus after DMS popouts/modals map.
hl.on("layer.opened", function(layer)
	local ns = layer and layer.namespace or ""
	if ns:sub(1, 4) ~= "dms:" then
		return
	end
	if ns:find(":background$") or ns:find(":clickcatcher$") then
		return
	end
	if ns:find("^dms:bar") or ns:find("wallpaper") or ns == "dms:tooltip" then
		return
	end
	local p = hl.get_cursor_pos()
	if not p then
		return
	end
	local x, y = p.x, p.y
	hl.dispatch(hl.dsp.cursor.move({ x = x + 1, y = y }))
	hl.timer(function()
		hl.dispatch(hl.dsp.cursor.move({ x = x, y = y }))
	end, { timeout = 1, type = "oneshot" })
end)

-- Smart borders & gaps: only when the workspace has a single tiled window
-- and no floating windows. `w[tv1]` alone still matches "1 tiled + N floating",
-- which zeroed borders/gaps on both the remaining tiled window and the float.
hl.workspace_rule({ workspace = "w[tv1] w[f0]", gaps_in = 0, gaps_out = 0, border_size = 0, no_border = true, no_rounding = true })
hl.workspace_rule({ workspace = "f[1] w[f0]", gaps_in = 0, gaps_out = 0, border_size = 0, no_border = true, no_rounding = true })
hl.window_rule({
	name = "smart-gaps-wtv1",
	match = { float = false, workspace = "w[tv1] w[f0]" },
	border_size = 0,
	rounding = 0,
})
hl.window_rule({
	name = "smart-gaps-f1",
	match = { float = false, workspace = "f[1] w[f0]" },
	border_size = 0,
	rounding = 0,
})
hl.window_rule({
	name = "smart-gaps-fullscreen",
	match = { fullscreen = true },
	border_size = 0,
	rounding = 0,
})

-- ThinkPad Lid Switch (blanks eDP-1 screen on lid close; dormant on desktop)
hl.bind("switch:on:Lid Switch", function()
	hl.timer(function()
		hl.dispatch(hl.dsp.dpms({ action = "off", monitor = "eDP-1" }))
	end, { timeout = 500, type = "oneshot" })
end, { locked = true, description = "Blank laptop screen on lid close" })

hl.bind("switch:off:Lid Switch", function()
	hl.timer(function()
		hl.dispatch(hl.dsp.dpms({ action = "on", monitor = "eDP-1" }))
	end, { timeout = 500, type = "oneshot" })
end, { locked = true, description = "Wake laptop screen on lid open" })

-- Machine-specific overrides (loaded if present, e.g. from desktop or laptop packages)
pcall(require, "desktop")
pcall(require, "laptop")

-- Snap layout drag bridge (all themes)
local snap_bridge = (os.getenv("HOME") or "") .. "/.local/lib/hyprland/hypr-snap-bridge-v3.so"
local f = io.open(snap_bridge, "r")
if f then
	f:close()
	pcall(hl.plugin.load, snap_bridge)
end
require("dms.snap")

-- hyprbars window title bars plugin
local hyprbars_plugin = (os.getenv("HOME") or "") .. "/.local/lib/hyprland/hyprbars.so"
local f_bars = io.open(hyprbars_plugin, "r")
if f_bars then
	f_bars:close()
	pcall(hl.plugin.load, hyprbars_plugin)


	_G.hyprbars_buttons_configured = false
	_G.setup_hyprbars_buttons = function(theme_style)
		if _G.hyprbars_buttons_configured then
			return
		end
		_G.hyprbars_buttons_configured = true
		pcall(function()
			if not (hl.plugin and hl.plugin.hyprbars and hl.plugin.hyprbars.add_button) then
				return
			end

			local hb = _G.dms_hyprbars or {}
			local bar_color = hb.bar_color or "rgba(1e1e1ecc)"
			local text_color = hb.text_color or "rgb(cccccc)"

			if theme_style == "windows-11" or theme_style == "windows-10" then
				hl.config({
					plugin = {
						hyprbars = {
							bar_height = 30,
							bar_color = bar_color,
							["col.text"] = text_color,
							bar_blur = true,
							bar_text_font = "Inter Variable",
							bar_text_size = 10,
							bar_title_padding = 14,
							bar_text_align = "left",
							bar_padding = 0,
							bar_button_padding = 0,
							bar_part_of_window = true,
							bar_precedence_over_border = true,
							on_double_click = "hyprctl dispatch fullscreen 1",
						},
					},
				})

				-- Windows 11 / 10 wide rectangular caption buttons (46px wide, full bar height)
				-- Close: red hover
				hl.plugin.hyprbars.add_button({
					bg_color = "rgba(00000000)",
					fg_color = text_color,
					size = 14,
					width = 46,
					round = 0,
					icon_size = 14,
					icon = "\u{e1b2}",
					action = "close",
				})
				-- Maximize / Restore
				hl.plugin.hyprbars.add_button({
					bg_color = "rgba(00000000)",
					fg_color = text_color,
					size = 14,
					width = 46,
					round = 0,
					icon_size = 14,
					icon = "\u{e167}",
					action = "fullscreen",
				})
				-- No minimize: Hyprland has no window hide, and this used to
				-- toggle tiled/floating. Close + maximize only.
			else
				-- Default theme: "rounded shit" (macOS / GNOME circular chiclets with glowing pills)
				hl.config({
					plugin = {
						hyprbars = {
							bar_height = 32,
							bar_color = bar_color,
							["col.text"] = text_color,
							bar_blur = true,
							bar_text_font = "Cantarell, Inter, Sans",
							bar_text_size = 11,
							bar_text_align = "left",
							bar_padding = 10,
							bar_button_padding = 8,
							bar_part_of_window = true,
							bar_precedence_over_border = true,
							on_double_click = "hyprctl dispatch fullscreen 1",
						},
					},
				})

				-- Close: circular red chiclet
				hl.plugin.hyprbars.add_button({
					bg_color = "rgba(ff5f57dd)",
					fg_color = "rgb(440000)",
					size = 18,
					width = 18,
					height = 18,
					round = 99,
					icon_size = 12,
					icon = "\u{e1b2}",
					action = "close",
				})
				-- Maximize: circular green chiclet
				hl.plugin.hyprbars.add_button({
					bg_color = "rgba(40c940dd)",
					fg_color = "rgb(003300)",
					size = 18,
					width = 18,
					height = 18,
					round = 99,
					icon_size = 12,
					icon = "\u{e167}",
					action = "fullscreen",
				})
			end
		end)
	end
end

-- Active theme overrides (managed by theme-switcher)
pcall(require, "theme")

-- If theme didn't call setup_hyprbars_buttons, call it with fallback detection
if _G.setup_hyprbars_buttons then
	local f_th = io.open((os.getenv("HOME") or "") .. "/.config/.current_theme", "r")
	local cur_theme = "default"
	if f_th then
		cur_theme = f_th:read("*l") or "default"
		f_th:close()
	end
	_G.setup_hyprbars_buttons(cur_theme)
end

