-- Hyprland configuration (Lua) — https://wiki.hypr.land/Configuring/Start/
-- Unified base configuration across all machines.
-- DMS-managed fragments live in ~/.config/hypr/dms/ and are required below.

hl.config({ autogenerated = false })

-------------------------------
---- ENVIRONMENT VARIABLES ----
-------------------------------

hl.env("QT_QPA_PLATFORM", "wayland")
hl.env("QT_QPA_PLATFORMTHEME", "gtk3")
hl.env("QT_QPA_PLATFORMTHEME_QT6", "gtk3")
hl.env("ELECTRON_OZONE_PLATFORM_HINT", "auto")
hl.env("TERMINAL", "ghostty")

-------------------
---- AUTOSTART ----
-------------------

-- DMS_STARTUP_BEGIN
hl.on("hyprland.start", function()
	hl.exec_cmd("dbus-update-activation-environment --systemd --all")
	hl.exec_cmd("systemctl --user start hyprland-session.target")
end)
-- DMS_STARTUP_END

-- User autostart
hl.on("hyprland.start", function()
	hl.exec_cmd("wl-paste --watch cliphist store")
end)

-----------------------
---- LOOK AND FEEL ----
-----------------------

hl.config({
	binds = {
		allow_pin_fullscreen = true,
	},
	input = {
		kb_layout = "us,gr",
		kb_options = "",
		repeat_delay = 300,
		numlock_by_default = true,
		-- Click to activate (Win11). Hovering a float must not yank focus.
		follow_mouse = 2,
		float_switch_override_focus = 0,
		mouse_refocus = false,
		accel_profile = "flat",
		sensitivity = 0.0,
		touchpad = {
			tap_to_click = true,
			natural_scroll = true,
		},
	},
	general = {
		allow_tearing = true,
		gaps_in = 5,
		gaps_out = 5,
		border_size = 2,
		layout = "dwindle",
	},
	decoration = {
		rounding = 12,
		border_part_of_window = false,
		active_opacity = 1.0,
		inactive_opacity = 1.0,
		blur = {
			enabled = false,
		},
		shadow = {
			enabled = true,
			range = 30,
			render_power = 5,
			offset = "0 5",
			color = "rgba(00000070)",
		},
	},
	misc = {
		disable_hyprland_logo = true,
		disable_splash_rendering = true,
		vrr = 1,
	},
	cursor = {
		no_hardware_cursors = 0,
		use_cpu_buffer = 0,
		no_warps = true,
	},
	dwindle = {
		preserve_split = true,
	},
	master = {
		mfact = 0.5,
	},
})

-- ThinkPad TrackPoint (disables touchpad to prevent palm jitter; dormant on desktop)
hl.device({
	name = "synaptics-tm2722-001",
	enabled = false,
})
hl.device({
	name = "synps/2-synaptics-touchpad",
	enabled = false,
})

hl.animation({ leaf = "windowsIn", enabled = true, speed = 3, bezier = "default" })
hl.animation({ leaf = "windowsOut", enabled = true, speed = 3, bezier = "default" })
hl.animation({ leaf = "workspaces", enabled = true, speed = 5, bezier = "default" })
hl.animation({ leaf = "windowsMove", enabled = true, speed = 4, bezier = "default" })
hl.animation({ leaf = "fade", enabled = true, speed = 3, bezier = "default" })
hl.animation({ leaf = "border", enabled = true, speed = 3, bezier = "default" })

--------------------------------
---- WINDOWS AND WORKSPACES ----
--------------------------------

-- Stock DMS window / layer rules (user extras live in dms/windowrules.lua)
hl.window_rule({ match = { class = "^(org\\.wezfurlong\\.wezterm)$" }, tile = true })
hl.window_rule({ match = { class = "^(org\\.gnome\\.)" }, rounding = 12 })
hl.window_rule({ match = { class = "^(gnome-control-center)$" }, tile = true })
hl.window_rule({ match = { class = "^(pavucontrol)$" }, tile = true })
hl.window_rule({ match = { class = "^(nm-connection-editor)$" }, tile = true })
hl.window_rule({ match = { class = "^(org\\.gnome\\.Calculator)$" }, float = true })
hl.window_rule({ match = { class = "^(gnome-calculator)$" }, float = true })
hl.window_rule({ match = { class = "^(galculator)$" }, float = true })
hl.window_rule({ match = { class = "^(blueman-manager)$" }, float = true })
hl.window_rule({ match = { class = "^(org\\.gnome\\.Nautilus)$" }, float = true })
hl.window_rule({ match = { class = "^(xdg-desktop-portal)$" }, float = true })
hl.window_rule({
	match = { title = ".*[Pp]icture[- ][iI]n[- ][pP]icture.*" },
	float = true,
	pin = true,
})
hl.window_rule({ match = { class = "^(zoom)$" }, float = true })
hl.layer_rule({ match = { namespace = "^(quickshell)$" }, no_anim = true })
hl.layer_rule({ match = { namespace = "^dms:.*" }, no_anim = true })

-------------------------
---- DMS FRAGMENTS -----
-------------------------

require("dms.colors")
if not pcall(require, "dms.outputs") then
	hl.monitor({ output = "", mode = "preferred", position = "auto", scale = "auto" })
end
require("dms.layout")
require("dms.cursor")
require("dms.floating-mode")
require("dms.binds")
require("dms.binds-user")
require("dms.windowrules")
require("dms.steam-toasts")

-- Inactive color is fully transparent; border is drawn outside the window.
hl.config({
	general = {
		col = {
			inactive_border = "rgba(00000000)",
		},
	},
	decoration = {
		border_part_of_window = false,
	},
	input = {
		follow_mouse = 2,
		float_switch_override_focus = 0,
		mouse_refocus = false,
	},
})

-- Hyprland's CLayerSurface::onMap() forces pointer focus onto any newly mapped
-- OnDemand/Exclusive layer, even when the cursor is still over the bar. Clicks
-- then go to that layer (or nowhere, if they land in an input-region hole) until
-- the mouse moves. Re-hit-test pointer focus after DMS popouts/modals map.
hl.on("layer.opened", function(layer)
	local ns = layer and layer.namespace or ""
	if ns:sub(1, 4) ~= "dms:" then
		return
	end
	if ns:find(":background$") or ns:find(":clickcatcher$") then
		return
	end
	if ns:find("^dms:bar") or ns:find("wallpaper") or ns == "dms:tooltip" then
		return
	end
	local p = hl.get_cursor_pos()
	if not p then
		return
	end
	local x, y = p.x, p.y
	hl.dispatch(hl.dsp.cursor.move({ x = x + 1, y = y }))
	hl.timer(function()
		hl.dispatch(hl.dsp.cursor.move({ x = x, y = y }))
	end, { timeout = 1, type = "oneshot" })
end)

-- Smart borders & gaps: only when the workspace has a single tiled window
-- and no floating windows. `w[tv1]` alone still matches "1 tiled + N floating",
-- which zeroed borders/gaps on both the remaining tiled window and the float.
hl.workspace_rule({ workspace = "w[tv1] w[f0]", gaps_in = 0, gaps_out = 0, border_size = 0, no_border = true, no_rounding = true })
hl.workspace_rule({ workspace = "f[1] w[f0]", gaps_in = 0, gaps_out = 0, border_size = 0, no_border = true, no_rounding = true })
hl.window_rule({
	name = "smart-gaps-wtv1",
	match = { float = false, workspace = "w[tv1] w[f0]" },
	border_size = 0,
	rounding = 0,
})
hl.window_rule({
	name = "smart-gaps-f1",
	match = { float = false, workspace = "f[1] w[f0]" },
	border_size = 0,
	rounding = 0,
})
hl.window_rule({
	name = "smart-gaps-fullscreen",
	match = { fullscreen = true },
	border_size = 0,
	rounding = 0,
})

-- ThinkPad Lid Switch (blanks eDP-1 screen on lid close; dormant on desktop)
hl.bind("switch:on:Lid Switch", function()
	hl.timer(function()
		hl.dispatch(hl.dsp.dpms({ action = "off", monitor = "eDP-1" }))
	end, { timeout = 500, type = "oneshot" })
end, { locked = true, description = "Blank laptop screen on lid close" })

hl.bind("switch:off:Lid Switch", function()
	hl.timer(function()
		hl.dispatch(hl.dsp.dpms({ action = "on", monitor = "eDP-1" }))
	end, { timeout = 500, type = "oneshot" })
end, { locked = true, description = "Wake laptop screen on lid open" })

-- Machine-specific overrides (loaded if present, e.g. from desktop or laptop packages)
pcall(require, "desktop")
pcall(require, "laptop")

-- Windows 11 Snap layout drag bridge
local snap_bridge = (os.getenv("HOME") or "") .. "/.local/lib/hyprland/hypr-snap-bridge-v3.so"
local f = io.open(snap_bridge, "r")
if f then
	f:close()
	pcall(hl.plugin.load, snap_bridge)
end

-- hyprbars window title bars plugin
local hyprbars_plugin = (os.getenv("HOME") or "") .. "/.local/lib/hyprland/hyprbars.so"
local f_bars = io.open(hyprbars_plugin, "r")
if f_bars then
	f_bars:close()
	pcall(hl.plugin.load, hyprbars_plugin)

	local function get_monitor_work_area(mon)
		local is_rotated = (mon.transform and (mon.transform % 2 == 1))
		local scale = (mon.scale and mon.scale > 0) and mon.scale or 1
		local raw_w = is_rotated and mon.height or mon.width
		local raw_h = is_rotated and mon.width or mon.height
		local logical_w = math.floor(raw_w / scale + 0.5)
		local logical_h = math.floor(raw_h / scale + 0.5)

		local res = mon.reserved or {}
		local res_top = (res.top ~= nil) and res.top or 0
		local res_bottom = (res.bottom ~= nil) and res.bottom or 52
		local res_left = (res.left ~= nil) and res.left or 0
		local res_right = (res.right ~= nil) and res.right or 0

		return {
			x = mon.x + res_left,
			y = mon.y + res_top,
			w = logical_w - res_left - res_right,
			h = logical_h - res_top - res_bottom,
			screen_w = logical_w,
			screen_h = logical_h,
			res_top = res_top,
			res_bottom = res_bottom,
			res_left = res_left,
			res_right = res_right,
		}
	end

	_G.win11_toggle_maximize = function(target_addr)
		local w = (target_addr and hl.get_window("address:" .. target_addr)) or hl.get_active_window()
		if not w then
			return
		end

		_G.win11_snap_cache = _G.win11_snap_cache or {}
		local raw_addr = w.address:lower()
		local clean_addr = raw_addr:gsub("^0x", "")
		local full_addr = "0x" .. clean_addr

		local mon = (_G.resolve_window_monitor and _G.resolve_window_monitor(w))
			or (type(w.monitor) == "table" and w.monitor)
			or (hl.get_monitor_at_cursor and hl.get_monitor_at_cursor())
			or (hl.get_monitors() and hl.get_monitors()[1])
		if not mon then
			return
		end

		local wa = get_monitor_work_area(mon)

		-- Check whether window has hyprbars titlebar using centralized helper
		local has_bar = true
		if _G.window_has_hyprbar then
			has_bar = _G.window_has_hyprbar(w)
		end

		local title_h = has_bar and 30 or 0
		local max_x = wa.x
		local max_y = wa.y + title_h
		local max_w = wa.w
		local max_h = wa.h - title_h

		local is_currently_maximized = false
		local cached = _G.win11_snap_cache[full_addr] or _G.win11_snap_cache[clean_addr]
		local use_xdg = _G.window_uses_xdg_maximize and _G.window_uses_xdg_maximize(w)
		local transient = _G.window_is_transient_float and _G.window_is_transient_float(w)

		if math.abs(w.size.x - max_w) <= 4 and math.abs(w.size.y - max_h) <= 4
			and math.abs(w.at.x - max_x) <= 4 and math.abs(w.at.y - max_y) <= 4 then
			is_currently_maximized = true
		end
		if not transient and (w.fullscreen == 1 or w.fullscreen == 3) then
			is_currently_maximized = true
		end

		local function targeted_resize_move(win, x, y, width, height)
			if not win then
				return
			end
			pcall(function()
				hl.dispatch(hl.dsp.window.resize({ window = win, x = width, y = height, relative = false }))
				hl.dispatch(hl.dsp.window.move({ window = win, x = x, y = y }))
			end)
		end

		if is_currently_maximized then
			-- RESTORE (to pre-snap size and position)
			hl.dispatch(hl.dsp.window.set_prop({ window = "address:" .. full_addr, prop = "border_size", value = "unset" }))
			hl.dispatch(hl.dsp.window.set_prop({ window = "address:" .. full_addr, prop = "rounding", value = "unset" }))

			-- Never xdg-unmax transients: Firefox/Zen unmaxes the parent too.
			if use_xdg and (w.fullscreen == 1 or w.fullscreen == 3) then
				pcall(function()
					hl.dispatch(hl.dsp.window.fullscreen({ window = "address:" .. full_addr, mode = "maximized", action = "unset", layout_aware = false }))
				end)
			end

			local s = cached or { w = math.floor(wa.w * 0.6), h = math.floor(wa.h * 0.7) }
			_G.win11_snap_cache[full_addr] = nil
			_G.win11_snap_cache[clean_addr] = nil

			local newX = s.x or math.max(wa.x + 20, wa.x + math.floor((wa.w - s.w) / 2))
			local newY = s.y or math.max(wa.y + 40, wa.y + math.floor((wa.h - s.h) / 2))

			w = hl.get_window("address:" .. full_addr) or w
			targeted_resize_move(w, newX, newY, s.w, s.h)

			if _G.set_app_float_maximized then
				_G.set_app_float_maximized(w, false, "win11_toggle_maximize")
			end
		else
			-- MAXIMIZE (identical to dragging to top edge)
			if not w.floating then
				hl.dispatch(hl.dsp.window.float({ window = "address:" .. full_addr, action = "set" }))
			end

			_G.win11_snap_cache[full_addr] = { w = w.size.x, h = w.size.y, x = w.at.x, y = w.at.y }
			_G.win11_snap_cache[clean_addr] = _G.win11_snap_cache[full_addr]

			w = hl.get_window("address:" .. full_addr) or w
			if use_xdg then
				-- CSD: xdg maximize only. Geometry fill poisons native restore.
				pcall(function()
					hl.dispatch(hl.dsp.window.fullscreen({
						window = "address:" .. full_addr, mode = "maximized", action = "set",
					}))
					hl.dispatch(hl.dsp.window.set_prop({ window = "address:" .. full_addr, prop = "border_size", value = 0 }))
					hl.dispatch(hl.dsp.window.set_prop({ window = "address:" .. full_addr, prop = "rounding", value = 0 }))
				end)
			else
				targeted_resize_move(w, max_x, max_y, max_w, max_h)
				pcall(function()
					hl.dispatch(hl.dsp.window.set_prop({ window = "address:" .. full_addr, prop = "border_size", value = 0 }))
					hl.dispatch(hl.dsp.window.set_prop({ window = "address:" .. full_addr, prop = "rounding", value = 0 }))
				end)
			end

			if _G.set_app_float_maximized then
				_G.set_app_float_maximized(w, true, "win11_toggle_maximize")
			end
		end
		return (hl.dsp and hl.dsp.no_op and hl.dsp.no_op()) or nil
	end

	local function get_zone_geometry(mon, zone, has_bar)
		local wa = get_monitor_work_area(mon)
		local title_h = has_bar and 30 or 0
		local gap = 8
		local w = wa.w
		local h = wa.h
		local half_w = math.floor(w / 2 + 0.5)
		local half_h = math.floor(h / 2 + 0.5)
		local two_thirds_w = math.floor(w * 0.67 + 0.5)
		local one_third_w = math.floor(w / 3 + 0.5)
		local two_thirds_h = math.floor(h * 0.67 + 0.5)
		local one_third_h = math.floor(h / 3 + 0.5)

		local zx, zy, zw, zh = 0, 0, w, h
		if zone == "maximize" then
			zx, zy, zw, zh = 0, title_h, w, h - title_h
		elseif zone == "half-left" or zone == "left" then
			zx, zy = gap, gap + title_h
			zw, zh = half_w - (gap * 1.5), h - (gap * 2) - title_h
		elseif zone == "half-right" or zone == "right" then
			zx, zy = half_w + (gap * 0.5), gap + title_h
			zw, zh = half_w - (gap * 1.5), h - (gap * 2) - title_h
		elseif zone == "half-top" or zone == "top" then
			zx, zy = gap, gap + title_h
			zw, zh = w - (gap * 2), half_h - (gap * 1.5) - title_h
		elseif zone == "half-bottom" or zone == "bottom" then
			zx, zy = gap, half_h + (gap * 0.5) + title_h
			zw, zh = w - (gap * 2), half_h - (gap * 1.5) - title_h
		elseif zone == "left-two-thirds" then
			zx, zy = gap, gap + title_h
			zw, zh = two_thirds_w - (gap * 1.5), h - (gap * 2) - title_h
		elseif zone == "right-one-third" then
			zx, zy = two_thirds_w + (gap * 0.5), gap + title_h
			zw, zh = (w - two_thirds_w) - (gap * 1.5), h - (gap * 2) - title_h
		elseif zone == "top-two-thirds" then
			zx, zy = gap, gap + title_h
			zw, zh = w - (gap * 2), two_thirds_h - (gap * 1.5) - title_h
		elseif zone == "bottom-one-third" then
			zx, zy = gap, two_thirds_h + (gap * 0.5) + title_h
			zw, zh = w - (gap * 2), (h - two_thirds_h) - (gap * 1.5) - title_h
		elseif zone == "col-1" then
			zx, zy = gap, gap + title_h
			zw, zh = one_third_w - (gap * 1.5), h - (gap * 2) - title_h
		elseif zone == "col-2" then
			zx, zy = one_third_w + (gap * 0.5), gap + title_h
			zw, zh = one_third_w - gap, h - (gap * 2) - title_h
		elseif zone == "col-3" then
			zx, zy = (one_third_w * 2) + (gap * 0.5), gap + title_h
			zw, zh = (w - (one_third_w * 2)) - (gap * 1.5), h - (gap * 2) - title_h
		elseif zone == "row-1" then
			zx, zy = gap, gap + title_h
			zw, zh = w - (gap * 2), one_third_h - (gap * 1.5) - title_h
		elseif zone == "row-2" then
			zx, zy = gap, one_third_h + (gap * 0.5) + title_h
			zw, zh = w - (gap * 2), one_third_h - gap - title_h
		elseif zone == "row-3" then
			zx, zy = gap, (one_third_h * 2) + (gap * 0.5) + title_h
			zw, zh = w - (gap * 2), (h - (one_third_h * 2)) - (gap * 1.5) - title_h
		elseif zone == "top-left" then
			zx, zy = gap, gap + title_h
			zw, zh = half_w - (gap * 1.5), half_h - (gap * 1.5) - title_h
		elseif zone == "top-right" then
			zx, zy = half_w + (gap * 0.5), gap + title_h
			zw, zh = half_w - (gap * 1.5), half_h - (gap * 1.5) - title_h
		elseif zone == "bottom-left" then
			zx, zy = gap, half_h + (gap * 0.5) + title_h
			zw, zh = half_w - (gap * 1.5), half_h - (gap * 1.5) - title_h
		elseif zone == "bottom-right" then
			zx, zy = half_w + (gap * 0.5), half_h + (gap * 0.5) + title_h
			zw, zh = half_w - (gap * 1.5), half_h - (gap * 1.5) - title_h
		end

		return {
			x = wa.x + math.floor(zx),
			y = wa.y + math.floor(zy),
			w = math.floor(zw),
			h = math.floor(zh),
		}
	end

	_G.win11_snap_window = function(target_addr, zone, screen_name)
		if not zone or zone == "" then
			return (hl.dsp and hl.dsp.no_op and hl.dsp.no_op()) or nil
		end
		if zone == "maximize" then
			if _G.win11_toggle_maximize then
				return _G.win11_toggle_maximize(target_addr)
			end
			return (hl.dsp and hl.dsp.no_op and hl.dsp.no_op()) or nil
		end

		local w = (target_addr and target_addr ~= "" and hl.get_window("address:" .. target_addr)) or hl.get_active_window()
		if not w then
			return (hl.dsp and hl.dsp.no_op and hl.dsp.no_op()) or nil
		end

		local raw_addr = w.address:lower()
		local clean_addr = raw_addr:gsub("^0x", "")
		local full_addr = "0x" .. clean_addr

		local mon = nil
		if screen_name and screen_name ~= "" then
			for _, m in ipairs(hl.get_monitors() or {}) do
				if m.name == screen_name then
					mon = m
					break
				end
			end
		end
		if not mon then
			mon = w.monitor or (hl.get_monitors() and hl.get_monitors()[1])
		end
		if not mon then
			return (hl.dsp and hl.dsp.no_op and hl.dsp.no_op()) or nil
		end

		if not w.floating then
			hl.dispatch(hl.dsp.window.float({ window = "address:" .. full_addr, action = "set" }))
		end

		_G.win11_snap_cache = _G.win11_snap_cache or {}
		if not _G.win11_snap_cache[full_addr] and not _G.win11_snap_cache[clean_addr] then
			_G.win11_snap_cache[full_addr] = { w = w.size.x, h = w.size.y, x = w.at.x, y = w.at.y }
			_G.win11_snap_cache[clean_addr] = _G.win11_snap_cache[full_addr]
		end

		local has_bar = true
		if _G.window_has_hyprbar then
			has_bar = _G.window_has_hyprbar(w)
		end

		local geom = get_zone_geometry(mon, zone, has_bar)

		w = hl.get_window("address:" .. full_addr) or w
		pcall(function()
			hl.dispatch(hl.dsp.window.resize({ window = w, x = geom.w, y = geom.h, relative = false }))
			hl.dispatch(hl.dsp.window.move({ window = w, x = geom.x, y = geom.y }))
			hl.dispatch(hl.dsp.window.set_prop({ window = "address:" .. full_addr, prop = "border_size", value = "unset" }))
			hl.dispatch(hl.dsp.window.set_prop({ window = "address:" .. full_addr, prop = "rounding", value = "unset" }))
		end)
		if _G.set_app_float_maximized then
			_G.set_app_float_maximized(w, false, "win11_snap")
		end
		return (hl.dsp and hl.dsp.no_op and hl.dsp.no_op()) or nil
	end

	-- Keep the drag grab under the cursor after unmax/unsnap.
	-- X is proportional (grab 30% from the left of a maxed window stays 30%
	-- from the left of the restored size). Y is the original titlebar offset
	-- (hyprbar grabs sit above the window, so this can be negative).
	local function follow_cursor_restore_pos(cursorX, cursorY, grabX, grabY, oldW, newW)
		cursorX = tonumber(cursorX) or 0
		cursorY = tonumber(cursorY) or 0
		grabX = tonumber(grabX) or 0
		grabY = tonumber(grabY) or 0
		oldW = tonumber(oldW) or 0
		newW = tonumber(newW) or 0
		local ratio = 0.5
		if oldW > 1 then
			ratio = grabX / oldW
		end
		if ratio < 0.05 then
			ratio = 0.05
		elseif ratio > 0.95 then
			ratio = 0.95
		end
		local offsetX = (newW > 0) and (newW * ratio) or 0
		return math.floor(cursorX - offsetX + 0.5), math.floor(cursorY - grabY + 0.5)
	end

	_G.win11_restore_window = function(target_addr, posX, posY, grabX, grabY)
		local w = (target_addr and target_addr ~= "" and hl.get_window("address:" .. target_addr)) or hl.get_active_window()
		if not w or not w.floating then
			return (hl.dsp and hl.dsp.no_op and hl.dsp.no_op()) or nil
		end

		local raw_addr = w.address:lower()
		local clean_addr = raw_addr:gsub("^0x", "")
		local full_addr = "0x" .. clean_addr

		local currently_max = (_G.window_is_float_maximized and _G.window_is_float_maximized(w))
			or (w.fullscreen == 1 or w.fullscreen == 3)
		local use_xdg = _G.window_uses_xdg_maximize and _G.window_uses_xdg_maximize(w)

		local cached = _G.win11_snap_cache and (_G.win11_snap_cache[full_addr] or _G.win11_snap_cache[clean_addr])

		-- Normal (not snapped/maxed) drag-drop: do not resize. Only unsnap/unmax.
		if not cached and not currently_max then
			return (hl.dsp and hl.dsp.no_op and hl.dsp.no_op()) or nil
		end

		-- Capture grab against the pre-unmax geometry. Unset / CSD restore
		-- would otherwise make cursor-window look like a center grab.
		local live = hl.get_cursor_pos()
		local cursorX = (live and live.x) or tonumber(posX) or 0
		local cursorY = (live and live.y) or tonumber(posY) or 0
		local winX, winY, oldW = w.at.x, w.at.y, w.size.x
		local usedGrabX = tonumber(grabX)
		local usedGrabY = tonumber(grabY)
		if not usedGrabX or usedGrabX < -90000 then
			usedGrabX = cursorX - winX
		end
		if not usedGrabY or usedGrabY < -90000 then
			usedGrabY = cursorY - winY
		end

		_G.win11_drag_restore = true

		hl.dispatch(hl.dsp.window.set_prop({ window = "address:" .. full_addr, prop = "border_size", value = "unset" }))
		hl.dispatch(hl.dsp.window.set_prop({ window = "address:" .. full_addr, prop = "rounding", value = "unset" }))
		pcall(function()
			hl.dispatch(hl.dsp.window.set_prop({ window = "address:" .. full_addr, prop = "no_anim", value = "1" }))
		end)

		-- Geometry-only transients (PiP) must not xdg-unmax: that unmaxes the parent.
		if use_xdg and (w.fullscreen == 1 or w.fullscreen == 3) then
			pcall(function()
				hl.dispatch(hl.dsp.window.fullscreen({
					window = "address:" .. full_addr, mode = "maximized", action = "unset", layout_aware = false,
				}))
			end)
		end

		if _G.set_app_float_maximized then
			_G.set_app_float_maximized(w, false, "win11_restore")
		end

		if _G.win11_snap_cache then
			_G.win11_snap_cache[full_addr] = nil
			_G.win11_snap_cache[clean_addr] = nil
		end

		local mon = (_G.resolve_window_monitor and _G.resolve_window_monitor(w))
			or (type(w.monitor) == "table" and w.monitor)
			or (hl.get_monitors() and hl.get_monitors()[1])
		local wa = mon and get_monitor_work_area(mon) or { x = 0, y = 0, w = 1920, h = 1080 }
		local dw = math.min(1280, math.max(400, math.floor(wa.w * 0.6)))
		local dh = math.min(800, math.max(300, math.floor(wa.h * 0.7)))
		local s = cached or { w = dw, h = dh }

		w = hl.get_window("address:" .. full_addr) or w
		local newX, newY = follow_cursor_restore_pos(cursorX, cursorY, usedGrabX, usedGrabY, oldW, s.w)
		pcall(function()
			hl.dispatch(hl.dsp.window.resize({ window = w, x = s.w, y = s.h, relative = false }))
			hl.dispatch(hl.dsp.window.move({ window = w, x = newX, y = newY }))
		end)
		pcall(function()
			hl.dispatch(hl.dsp.window.set_prop({ window = "address:" .. full_addr, prop = "no_anim", value = "unset" }))
		end)
		hl.timer(function()
			_G.win11_drag_restore = false
		end, { timeout = 200, type = "oneshot" })
		return (hl.dsp and hl.dsp.no_op and hl.dsp.no_op()) or nil
	end

	_G.hyprbars_buttons_configured = false
	_G.setup_hyprbars_buttons = function(theme_style)
		if _G.hyprbars_buttons_configured then
			return
		end
		_G.hyprbars_buttons_configured = true
		pcall(function()
			if not (hl.plugin and hl.plugin.hyprbars and hl.plugin.hyprbars.add_button) then
				return
			end

			local hb = _G.dms_hyprbars or {}
			local bar_color = hb.bar_color or "rgba(1e1e1ecc)"
			local text_color = hb.text_color or "rgb(cccccc)"

			if theme_style == "windows-11" or theme_style == "windows-10" then
				hl.config({
					plugin = {
						hyprbars = {
							bar_height = 30,
							bar_color = bar_color,
							["col.text"] = text_color,
							bar_blur = true,
							bar_text_font = "Inter Variable",
							bar_text_size = 10,
							bar_title_padding = 14,
							bar_text_align = "left",
							bar_padding = 0,
							bar_button_padding = 0,
							bar_part_of_window = true,
							bar_precedence_over_border = true,
							on_double_click = "hyprctl dispatch fullscreen 1",
						},
					},
				})

				-- Windows 11 / 10 wide rectangular caption buttons (46px wide, full bar height)
				-- Close: red hover
				hl.plugin.hyprbars.add_button({
					bg_color = "rgba(00000000)",
					fg_color = text_color,
					size = 14,
					width = 46,
					round = 0,
					icon_size = 14,
					icon = "\u{e1b2}",
					action = "close",
				})
				-- Maximize / Restore
				hl.plugin.hyprbars.add_button({
					bg_color = "rgba(00000000)",
					fg_color = text_color,
					size = 14,
					width = 46,
					round = 0,
					icon_size = 14,
					icon = "\u{e167}",
					action = "fullscreen",
				})
				-- No minimize: Hyprland has no window hide, and this used to
				-- toggle tiled/floating. Close + maximize only.
			else
				-- Default theme: "rounded shit" (macOS / GNOME circular chiclets with glowing pills)
				hl.config({
					plugin = {
						hyprbars = {
							bar_height = 32,
							bar_color = bar_color,
							["col.text"] = text_color,
							bar_blur = true,
							bar_text_font = "Cantarell, Inter, Sans",
							bar_text_size = 11,
							bar_text_align = "left",
							bar_padding = 10,
							bar_button_padding = 8,
							bar_part_of_window = true,
							bar_precedence_over_border = true,
							on_double_click = "hyprctl dispatch fullscreen 1",
						},
					},
				})

				-- Close: circular red chiclet
				hl.plugin.hyprbars.add_button({
					bg_color = "rgba(ff5f57dd)",
					fg_color = "rgb(440000)",
					size = 18,
					width = 18,
					height = 18,
					round = 99,
					icon_size = 12,
					icon = "\u{e1b2}",
					action = "close",
				})
				-- Maximize: circular green chiclet
				hl.plugin.hyprbars.add_button({
					bg_color = "rgba(40c940dd)",
					fg_color = "rgb(003300)",
					size = 18,
					width = 18,
					height = 18,
					round = 99,
					icon_size = 12,
					icon = "\u{e167}",
					action = "fullscreen",
				})
			end
		end)
	end
end

-- Active theme overrides (managed by theme-switcher)
pcall(require, "theme")

-- If theme didn't call setup_hyprbars_buttons, call it with fallback detection
if _G.setup_hyprbars_buttons then
	local f_th = io.open((os.getenv("HOME") or "") .. "/.config/.current_theme", "r")
	local cur_theme = "default"
	if f_th then
		cur_theme = f_th:read("*l") or "default"
		f_th:close()
	end
	_G.setup_hyprbars_buttons(cur_theme)
end

